image: alpine/edge
packages:
  - rust
  - cargo
  - sqlite-dev
sources:
  - https://git.sr.ht/~koehr/k0r
artifacts:
  - k0r/target/release/k0r
  - k0r/db/schema.sql
  - k0r/db/test_data.sql
  - k0r/LICENSE
  - k0r/README.md
tasks:
  - build: |
      cd k0r
      cargo build --release
