[package]
name = "k0r-url-shortener"
version = "0.1.0"
authors = ["koehr <n@koehr.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
radix_fmt = "1"
url = "2.2.0"

[features]
debug-output = []
