CREATE TABLE Users(
  UserID   INTEGER PRIMARY KEY,
  APIKey    TEXT NOT NULL,
  RateLimit INTEGER
);

CREATE TABLE URLs(
  ID      INTEGER PRIMARY KEY,
  URL     TEXT NOT NULL,
  Visits  INTEGER DEFAULT 0,
  UserID INTEGER NOT NULL,
  FOREIGN KEY(UserID) REFERENCES Users(UserID)
);
