CREATE TABLE Users(
  UserID   INTEGER PRIMARY KEY,
  APIKey    TEXT UNIQUE NOT NULL,
  RateLimit INTEGER DEFAULT 0,
  Admin     SMALLINT DEFAULT 0
);
CREATE UNIQUE INDEX idx_api_key ON Users(APIKey);

CREATE TABLE URLs(
  ID      INTEGER PRIMARY KEY,
  URL     TEXT NOT NULL,
  Visits  INTEGER DEFAULT 0,
  UserID INTEGER NOT NULL,
  FOREIGN KEY(UserID) REFERENCES Users(UserID)
);
